const data = {
  products: [
    {
      _id: '1',
      name: 'College Polo',
      slug: 'college polo',
      category: 'Polo',
      images: '/images/1.png', //679px x 829px
      price: 380,
      countInStock: 3,
      brand: 'Uniform',
      rating: 3,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'College Pants',
      slug: 'college pants',
      category: 'Pants',
      images: '/images/2.png', //679px x 829px
      price: 420,
      countInStock: 10,
      brand: 'Uniform',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '3',
      name: 'College Blouse',
      slug: 'college blouse',
      category: 'Blouse',
      images: '/images/3.png', //679px x 829px
      price: 400,
      countInStock: 10,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '4',
      name: 'College Skirt',
      slug: 'collge skirt',
      category: 'Skirts',
      images: '/images/4.png', //679px x 829px
      price: 340,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '5',
      name: 'Men PE T-Shirt',
      slug: 'pe t-shirt',
      category: 'PE',
      images: '/images/5.png', //679px x 829px
      price: 260,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '6',
      name: 'Women PE T-Shirt',
      slug: 'women pe t-shirt',
      category: 'PE',
      images: '/images/6.png', //679px x 829px
      price: 260,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '7',
      name: 'College PE Pants',
      slug: 'college pe pants',
      category: 'Pants',
      images: '/images/7.png', //679px x 829px
      price: 400,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '8',
      name: 'Senior High School Polo',
      slug: 'senior high school polo',
      category: 'Polo',
      images: '/images/8.png', //679px x 829px
      price: 370,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '9',
      name: 'Senior High School Pants',
      slug: 'senior high school pants',
      category: 'Pants',
      images: '/images/9.png', //679px x 829px
      price: 420,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '10',
      name: 'Senior High School Blouse',
      slug: 'senior high school blouse',
      category: 'Blouse',
      images: '/images/10.png', //679px x 829px
      price: 380,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '11',
      name: 'Senior High School Skirt',
      slug: 'senior high school skirt',
      category: 'Skirt',
      images: '/images/11.png', //679px x 829px
      price: 360,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '12',
      name: 'Senior High School Cravat',
      slug: 'senior high school cravat',
      category: 'Cravat',
      images: '/images/12.png', //679px x 829px
      price: 100,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '13',
      name: 'Senior High School PE T-Shirt',
      slug: 'senior high school pe t-shirt',
      category: 'PE',
      images: '/images/13.png', //679px x 829px
      price: 260,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '14',
      name: 'Senior High School PE Pants',
      slug: 'senior high school pe pants',
      category: 'PE',
      images: '/images/14.png', //679px x 829px
      price: 400,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '15',
      name: 'Junior High School Polo',
      slug: 'junior high school polo',
      category: 'Polo',
      images: '/images/15.png', //679px x 829px
      price: 370,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '16',
      name: 'Junior High School Pants',
      slug: 'junior high school pants',
      category: 'Pants',
      images: '/images/16.png', //679px x 829px
      price: 420,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '17',
      name: 'Junior High School Blouse',
      slug: 'junior high school Blouse',
      category: 'Blouse',
      images: '/images/17.png', //679px x 829px
      price: 380,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '18',
      name: 'Junior High School Skirt',
      slug: 'junior high school skirt',
      category: 'Skirt',
      images: '/images/18.png', //679px x 829px
      price: 360,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '19',
      name: 'Junior High School Caravat',
      slug: 'junior high school caravat',
      category: 'Caravat',
      images: '/images/19.png', //679px x 829px
      price: 100,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '20',
      name: 'Junior High School PE T-Shirt',
      slug: 'junior high school pe t-shirt',
      category: 'PE',
      images: '/images/13.png', //679px x 829px
      price: 260,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '21',
      name: 'Junior High School PE pants',
      slug: 'junior high school pe pants',
      category: 'PE',
      images: '/images/14.png', //679px x 829px
      price: 400,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '22',
      name: 'Elementary Polo',
      slug: 'elementary polo',
      category: 'Polo',
      images: '/images/20.png', //679px x 829px
      price: 310,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '23',
      name: 'Elementary Pants',
      slug: 'elemetary pants',
      category: 'Pants',
      images: '/images/9.png', //679px x 829px
      price: 420,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '24',
      name: 'Elementary Blouse',
      slug: 'elementary blouse',
      category: 'Blouse',
      images: '/images/17.png', //679px x 829px
      price: 340,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '25',
      name: 'Elementary Skirt',
      slug: 'elementary skirt',
      category: 'Skirt',
      images: '/images/18.png', //679px x 829px
      price: 360,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '26',
      name: 'Elementary Caravat',
      slug: 'elementary caravat',
      category: 'Caravat',
      images: '/images/19.png', //679px x 829px
      price: 100,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '27',
      name: 'Elementary PE T-Shirt',
      slug: 'elementary school pe t-shirt',
      category: 'PE',
      images: '/images/21.png', //679px x 829px
      price: 240,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '28',
      name: 'Elementary PE Pants',
      slug: 'elementary school pe pants',
      category: 'PE',
      images: '/images/22.png', //679px x 829px
      price: 360,
      countInStock: 0,
      brand: 'Uniform',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};
export default data;
